import React, { useState, useEffect } from 'react';
import { PublishedBlueprint } from '../types';
import { supabaseService } from '../services/supabaseService';
import { Calendar, Search, ArrowRight, Loader2, AlertCircle, Heart, Flame, Clock, ChevronDown } from 'lucide-react';
import { useQuery, keepPreviousData } from '@tanstack/react-query';
import { usePreferences } from '../contexts/PreferencesContext';
import { ANIMATION_CLASSES } from '../constants/animationConfig';
import { SHADOWS } from '../constants/shadowConfig';
import { DIRECTORY_CONFIG } from '../constants/displayConfig';

interface Props {
  onViewBlueprint: (_id: string) => void;
}

export const Directory: React.FC<Props> = ({ onViewBlueprint }) => {
  const { uiText } = usePreferences();
  
  // Search & Filter State
  const [searchTerm, setSearchTerm] = useState('');
  const [debouncedSearch, setDebouncedSearch] = useState('');
  const [sortBy, setSortBy] = useState<'newest' | 'popular'>('newest');
  const [limit, setLimit] = useState(DIRECTORY_CONFIG.DEFAULT_PAGE_SIZE);
  
  const [votingMap, setVotingMap] = useState<Record<string, boolean>>({}); // Track session votes

  // Debounce Search Logic
  useEffect(() => {
    const handler = setTimeout(() => {
      setDebouncedSearch(searchTerm);
      setLimit(DIRECTORY_CONFIG.DEFAULT_PAGE_SIZE); // Reset pagination on search
    }, 500);
    return () => clearTimeout(handler);
  }, [searchTerm]);

  // React Query Fetcher
  const fetchBlueprints = async ({ queryKey }: any) => {
    const [, search, sort, currentLimit] = queryKey;
    if (!supabaseService.isConfigured()) {
      throw new Error("Database connection not configured.");
    }
    // We modify searchPublicBlueprints to handle limit properly for infinite scroll simulation
    const page = 0; 
    return await supabaseService.searchPublicBlueprints(search, sort, page, currentLimit);
  };

  const { data: blueprints = [], isLoading, error, isPlaceholderData } = useQuery({
    queryKey: ['blueprints', debouncedSearch, sortBy, limit],
    queryFn: fetchBlueprints,
    placeholderData: keepPreviousData,
  });

  const handleLoadMore = () => {
    setLimit(prev => prev + 20);
  };

  const handleVote = async (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    if (supabaseService.hasVoted(id) || votingMap[id]) return;

    // Local Optimistic Update
    setVotingMap(prev => ({ ...prev, [id]: true }));
    await supabaseService.voteBlueprint(id);
  };

  return (
    <div className={`w-full max-w-7xl mx-auto px-4 py-12 ${ANIMATION_CLASSES.fadeIn.slow}`}>
      <div className="text-center mb-12">
        <h2 className="text-3xl md:text-5xl font-black text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-blue-500 mb-4">
          {uiText.directoryTitle || "Community Blueprints"}
        </h2>
        <p className="text-slate-400 text-lg max-w-2xl mx-auto">
          {uiText.directoryDesc || "Explore business systems and revenue models generated by the TrendVentures community."}
        </p>
      </div>

      <div className="flex flex-col md:flex-row gap-4 max-w-4xl mx-auto mb-12 items-center">
        <div className="relative flex-1 w-full">
          <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <Search className="h-5 w-5 text-slate-500" />
          </div>
          <input
            type="text"
            className="block w-full pl-10 pr-3 py-3 border border-slate-800 rounded-xl leading-5 bg-slate-900 text-slate-100 placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-emerald-500/50 focus:border-emerald-500 transition-all"
            placeholder={uiText.directorySearch || "Search niches or titles..."}
            aria-label={uiText.directorySearch || "Search niches or titles"}
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
        </div>
        
        <div className="flex bg-slate-900 p-1 rounded-xl border border-slate-800 shrink-0">
          <button 
            onClick={() => setSortBy('newest')}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-bold transition-all ${
              sortBy === 'newest' ? 'bg-slate-800 text-white shadow-sm' : 'text-slate-500 hover:text-slate-300'
            }`}
          >
            <Clock className="w-4 h-4" />
            {uiText.newest || "Newest"}
          </button>
          <button 
             onClick={() => setSortBy('popular')}
             className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-bold transition-all ${
               sortBy === 'popular' ? 'bg-slate-800 text-emerald-400 shadow-sm' : 'text-slate-500 hover:text-slate-300'
             }`}
          >
            <Flame className="w-4 h-4" />
            {uiText.popular || "Popular"}
          </button>
        </div>
      </div>

      {isLoading && !isPlaceholderData ? (
        <div className="flex flex-col items-center justify-center py-20">
          <Loader2 className="w-10 h-10 text-emerald-500 animate-spin mb-4" />
          <p className="text-slate-500">{uiText.loadingDirectory || "Loading blueprints..."}</p>
        </div>
      ) : error ? (
        <div className="text-center py-20 bg-red-900/10 rounded-2xl border border-red-500/20">
          <AlertCircle className="w-10 h-10 text-red-500 mx-auto mb-4" />
          <p className="text-red-400">{(error as Error).message}</p>
        </div>
      ) : blueprints.length === 0 ? (
        <div className="text-center py-20">
          <p className="text-slate-500 text-lg">{uiText.noResults || "No blueprints found."}</p>
        </div>
      ) : (
        <>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {blueprints.map((bp: PublishedBlueprint) => {
              // Merge API data with local optimistic state
              const hasVoted = supabaseService.hasVoted(bp.id) || votingMap[bp.id];
              const displayVotes = (bp.votes || 0) + (votingMap[bp.id] && !supabaseService.hasVoted(bp.id) ? 1 : 0);
              
              return (
                <div 
                  key={bp.id}
                  onClick={() => onViewBlueprint(bp.id)}
                  className={`group bg-slate-900 border border-slate-800 hover:border-emerald-500/50 rounded-xl p-6 transition-all hover:${SHADOWS.glow.emerald.md} cursor-pointer flex flex-col h-full relative overflow-hidden ${ANIMATION_CLASSES.fadeIn.normal}`}
                >
                  <div className="flex justify-between items-start mb-3 relative z-10">
                    <span className="text-xs font-bold px-2 py-1 rounded bg-slate-800 text-emerald-400 border border-slate-700/50">
                      {bp.niche}
                    </span>
                    <div className="flex items-center gap-3">
                       <span className="text-[10px] text-slate-500 flex items-center gap-1">
                        <Calendar className="w-3 h-3" />
                        {new Date(bp.created_at).toLocaleDateString()}
                      </span>
                      <button 
                        onClick={(e) => handleVote(e, bp.id)}
                        disabled={hasVoted}
                        className={`flex items-center gap-1 text-xs font-bold px-2 py-1 rounded-full border transition-all ${
                           hasVoted 
                           ? 'bg-red-500/10 border-red-500/20 text-red-400' 
                           : 'bg-slate-800 border-slate-700 text-slate-400 hover:text-red-400 hover:border-red-500/30'
                        }`}
                      >
                        <Heart className={`w-3 h-3 ${hasVoted ? 'fill-red-400' : ''}`} />
                        {displayVotes}
                      </button>
                    </div>
                  </div>
                  
                  <h3 className="text-xl font-bold text-slate-100 mb-2 group-hover:text-emerald-400 transition-colors line-clamp-2 relative z-10">
                    {bp.title}
                  </h3>
                  
                  <p className="text-slate-400 text-sm mb-4 line-clamp-3 flex-grow relative z-10">
                    {bp.summary}
                  </p>

                  <div className="mt-auto pt-4 border-t border-slate-800/50 flex items-center justify-between relative z-10">
                    <div className="flex items-center gap-2">
                      <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-blue-900/20 text-blue-400 border border-blue-500/20">
                        {bp.full_data.idea.type}
                      </span>
                      <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-purple-900/20 text-purple-400 border border-purple-500/20">
                         {bp.full_data.idea.monetizationModel}
                      </span>
                    </div>
                    <div className="w-8 h-8 rounded-full bg-slate-800 flex items-center justify-center group-hover:bg-emerald-500 group-hover:text-slate-900 transition-colors">
                      <ArrowRight className="w-4 h-4" />
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Load More Button */}
          {blueprints.length >= limit && (
            <div className="mt-12 text-center">
               <button
                 onClick={handleLoadMore}
                 disabled={isLoading}
                 className="bg-slate-800 hover:bg-slate-700 text-slate-300 font-bold py-3 px-8 rounded-full border border-slate-700 transition-all flex items-center gap-2 mx-auto disabled:opacity-50"
               >
                 {isLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <ChevronDown className="w-4 h-4" />}
                 Load More Results
               </button>
            </div>
          )}
        </>
      )}
    </div>
  );
};